# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Configuracion inicial
    init: |
      npm install
      brew install planetscale/tap/pscale
      brew install mysql-client
      brew upgrade pscale
    command: echo 'start script'

